import { GoogleGenerativeAIEmbeddings } from "@langchain/google-genai";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env" });

async function testEmbeddingDimensions() {
    console.log("🧪 Testing Embedding Dimensions\n");
    console.log("=" + "=".repeat(70) + "\n");

    const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;

    if (!GOOGLE_API_KEY) {
        console.log("❌ GOOGLE_API_KEY not set!\n");
        return false;
    }

    console.log("Environment:");
    console.log(`  GOOGLE_API_KEY: ✅ Set (length: ${GOOGLE_API_KEY.length})\n`);

    try {
        console.log("1️⃣  Initializing gemini-embedding-001...");
        const embeddings = new GoogleGenerativeAIEmbeddings({
            modelName: "gemini-embedding-001",
            apiKey: GOOGLE_API_KEY,
        });
        console.log("   ✅ Model initialized\n");

        console.log("2️⃣  Generating test embedding...");
        const testText = "What is Section 302 of PPC?";
        console.log(`   Text: "${testText}"`);

        const vector = await embeddings.embedQuery(testText);

        console.log("   ✅ Embedding generated");
        console.log(`   Dimension: ${vector.length}`);
        console.log(`   Sample values: [${vector.slice(0, 5).map(v => v.toFixed(4)).join(", ")}...]\n`);

        console.log("=" + "=".repeat(70));
        console.log("\n🔍 DIAGNOSIS:\n");
        console.log(`   Current Pinecone Index: 768 dimensions`);
        console.log(`   gemini-embedding-001: ${vector.length} dimensions`);

        if (vector.length !== 768) {
            console.log("\n❌ DIMENSION MISMATCH DETECTED!");
            console.log("\n   This is why RAG retrieval is failing!");
            console.log("   The embeddings generated by gemini-embedding-001 have");
            console.log(`   ${vector.length} dimensions, but your Pinecone index expects 768.\n`);
            console.log("   SOLUTION:");
            console.log("   Option 1: Re-create Pinecone index with correct dimensions");
            console.log("   Option 2: Use a different embedding model that outputs 768 dimensions");
            console.log("   Option 3: Re-ingest all documents with gemini-embedding-001\n");
            return false;
        } else {
            console.log("\n✅ Dimensions match! The issue is elsewhere.\n");
            return true;
        }

    } catch (error: any) {
        console.log("\n❌ ERROR:", error.message, "\n");
        return false;
    }
}

testEmbeddingDimensions()
    .then(success => process.exit(success ? 0 : 1))
    .catch(error => {
        console.error("Fatal error:", error);
        process.exit(1);
    });
